function validation = validateMainSimulation( ...
    truth,fog,caig,caigPhysics,sync,results,cfg)
%VALIDATEMAINSIMULATION Run the baseline software-regression checks.
%
% These checks do not define physical hardware requirements. Validation
% and plotting intentionally contain no random-number generation.

    validation.checkPhase = ...
        caigPhysics.maxRateError<1e-12;

    validation.checkSync = ...
        max(sync.maxSyncDifference)<1e-12 ...
        &&sync.maxTimestampError<1e-12;

    validation.fogSigmaRelativeError = ...
        abs(fog.sigmaEmpirical/fog.sigmaExpected-1);
    validation.checkFOGNoise = ...
        all(validation.fogSigmaRelativeError ...
        <cfg.noiseRelativeTolerance);

    validation.caigSigmaRelativeError = ...
        abs(caig.sigmaEmpirical/caig.sigmaExpected-1);
    validation.checkCAIGNoise = ...
        all(validation.caigSigmaRelativeError ...
        <cfg.noiseRelativeTolerance);

    validation.regressionPhiDifference = ...
        max(abs(results.finalMisalignmentDeg-cfg.referencePhiDeg));

    validation.regressionBiasDifference = ...
        max(abs(results.finalBiasDegH-cfg.referenceBiasDeg_h));

    validation.checkKalmanRegression = ...
        validation.regressionPhiDifference<cfg.regressionTolerance ...
        &&validation.regressionBiasDifference<cfg.regressionTolerance;

    validation.allPass = ...
        validation.checkPhase ...
        &&validation.checkSync ...
        &&validation.checkFOGNoise ...
        &&validation.checkCAIGNoise ...
        &&validation.checkKalmanRegression;

    % Keep inputs explicit in the interface and guard their expected sizes.
    validation.expectedFOGRows = truth.NFOG;
    validation.expectedCAIGRows = truth.NCAIG;
end
