%% CAIG_V2_6_duration_study_timetable.m
%
% Observation-duration study for the noisy CAIG + FOG
% six-state Kalman estimator using MATLAB timetable-based
% synchronization.
%
% Main architecture:
%   Zhang et al. (2019)
%
% This script is an architectural refactor of V2.6.
%
% OLD:
%   OmegaFOG(1:20:end,:)
%
% NEW:
%   timetable + retime
%
% Scientific parameters are intentionally unchanged.
%
%
% Durations:
%   120 s
%   300 s
%   600 s
%
% Monte Carlo:
%   100 runs per duration
%
%
% FOG NOISE MODEL
% ----------------
%
% EMCORE EG-1300:
%
%   ARW = 0.002 deg/sqrt(h)
%
% MATLAB noise convention:
%
%   NoiseType = 'single-sided'
%
% Therefore:
%
%   sigma_FOG = N_FOG * sqrt(Fs_FOG)
%
%
% CAIG NOISE MODEL
% ----------------
%
% Tackmann et al. (2012):
%
%   sensitivity = 6.1e-7 rad/s/sqrt(Hz)
%
% Current project baseline:
%
%   sigma_CAIG = N_CAIG * sqrt(Fs_CAIG/2)
%
%
% SYNCHRONIZATION
% ---------------
%
% FOG and CAIG measurements are stored as independent
% timetables.
%
% FOG is evaluated explicitly at CAIG timestamps using:
%
%   retime(...,'linear')
%
% For the current baseline the clocks are perfectly aligned,
% so retime should reproduce the old 1:20:end indexing to
% numerical precision.

clear;
clc;
close all;

%% ============================================================
% 1. GENERAL SETTINGS
% =============================================================

durations = ...
    [120 300 600];       % [s]

nRuns = ...
    100;

FsFOG = ...
    100;                 % [Hz] Zhang

FsCAIG = ...
    5;                   % [Hz] Zhang

sampleRatio = ...
    FsFOG/FsCAIG;

assert( ...
    mod(sampleRatio,1) == 0, ...
    'FOG/CAIG sample-rate ratio must be integer.');

fprintf('============================================\n');
fprintf('CAIG V2.6 - DURATION STUDY + TIMETABLE\n');
fprintf('============================================\n\n');

fprintf('Monte Carlo runs = %d\n', ...
    nRuns);

fprintf('FOG rate         = %.1f Hz\n', ...
    FsFOG);

fprintf('CAIG rate        = %.1f Hz\n', ...
    FsCAIG);

fprintf('Durations        = ');

fprintf('%.0f ', ...
    durations);

fprintf('s\n\n');

%% ============================================================
% 2. TRUE MISALIGNMENT
% =============================================================

phiTrueDeg = ...
    [1;2;3];

phiTrue = ...
    deg2rad(phiTrueDeg);

C_A_F = ...
    eye(3) ...
    - skewMatrix(phiTrue);

%% ============================================================
% 3. TRUE FOG BIAS
% =============================================================

biasFOG_deg_h = ...
    0.1;

biasFOG = ...
    deg2rad(biasFOG_deg_h)/3600;

biasFOGvec = ...
    biasFOG ...
    * ones(1,3);

%% ============================================================
% 4. FOG WHITE NOISE
% =============================================================

% EMCORE EG-1300 ARW

ARW_FOG_deg_sqrt_h = ...
    0.002;

% Convert:
%
% deg/sqrt(h)
% ->
% rad/sqrt(s)
%
% dimensionally equivalent to:
%
% (rad/s)/sqrt(Hz)

N_FOG = ...
    deg2rad(ARW_FOG_deg_sqrt_h) ...
    / sqrt(3600);

% Allan-variance validated single-sided scaling

sigmaFOG = ...
    N_FOG ...
    * sqrt(FsFOG);

fprintf('FOG NOISE MODEL\n');
fprintf('--------------------------------------------\n');

fprintf('ARW         = %.6f deg/sqrt(h)\n', ...
    ARW_FOG_deg_sqrt_h);

fprintf('NoiseType   = single-sided\n');

fprintf('N_FOG       = %.6e rad/s/sqrt(Hz)\n', ...
    N_FOG);

fprintf('sigma_FOG   = %.6e rad/s\n\n', ...
    sigmaFOG);

%% ============================================================
% 5. CAIG WHITE NOISE
% =============================================================

% Tackmann et al. (2012)

N_CAIG = ...
    6.1e-7;               % rad/s/sqrt(Hz)

% Current project baseline assumption

sigmaCAIG = ...
    N_CAIG ...
    * sqrt(FsCAIG/2);

fprintf('CAIG NOISE MODEL\n');
fprintf('--------------------------------------------\n');

fprintf('N_CAIG      = %.6e rad/s/sqrt(Hz)\n', ...
    N_CAIG);

fprintf('sigma_CAIG  = %.6e rad/s\n\n', ...
    sigmaCAIG);

%% ============================================================
% 6. OBSERVATION COVARIANCE
% =============================================================

% Independent FOG and CAIG white noise

sigmaZ = ...
    sqrt( ...
        sigmaFOG^2 ...
        + sigmaCAIG^2);

R = ...
    sigmaZ^2 ...
    * eye(3);

fprintf('OBSERVATION NOISE\n');
fprintf('--------------------------------------------\n');

fprintf('sigma_Z     = %.6e rad/s\n', ...
    sigmaZ);

fprintf('R diagonal  = %.6e (rad/s)^2\n\n', ...
    R(1,1));

%% ============================================================
% 7. KALMAN INITIAL CONDITIONS
% =============================================================

X0 = ...
    zeros(6,1);

% Zhang initial covariance

phiStd0 = ...
    deg2rad([1;2;3]);

biasStd0 = ...
    deg2rad([0.1;0.1;0.1]) ...
    /3600;

P0 = ...
    diag( ...
        [phiStd0;biasStd0].^2);

Phi = ...
    eye(6);

% Injected states are constant

Q = ...
    zeros(6);

I6 = ...
    eye(6);

%% ============================================================
% 8. STORAGE FOR DURATION RESULTS
% =============================================================

nDur = ...
    length(durations);

meanPhi_all = ...
    zeros(nDur,3);

stdPhi_all = ...
    zeros(nDur,3);

rmsePhi_all = ...
    zeros(nDur,3);

ciPhiLow_all = ...
    zeros(nDur,3);

ciPhiHigh_all = ...
    zeros(nDur,3);


meanBias_all = ...
    zeros(nDur,3);

stdBias_all = ...
    zeros(nDur,3);

rmseBias_all = ...
    zeros(nDur,3);

ciBiasLow_all = ...
    zeros(nDur,3);

ciBiasHigh_all = ...
    zeros(nDur,3);

%% ============================================================
% 9. STORAGE FOR TIMETABLE VALIDATION
% =============================================================

% Store the maximum difference between:
%
% timetable + retime
%
% and
%
% old manual indexing
%
% for every run and every duration.

maxMethodDifferenceAll = ...
    zeros(nDur,nRuns,3);

maxTimeDifferenceAll = ...
    zeros(nDur,nRuns);

%% ============================================================
% 10. LOOP OVER OBSERVATION DURATIONS
% =============================================================

for d = 1:nDur

    duration = ...
        durations(d);

    fprintf('============================================\n');
    fprintf('DURATION = %.0f s\n', ...
        duration);
    fprintf('============================================\n');

    %% --------------------------------------------------------
    % Time vectors
    % ---------------------------------------------------------

    dtFOG = ...
        1/FsFOG;

    dtCAIG = ...
        1/FsCAIG;

    tFOG = ...
        (0:dtFOG:duration-dtFOG).';

    tCAIG = ...
        (0:dtCAIG:duration-dtCAIG).';

    NFOG = ...
        length(tFOG);

    NCAIG = ...
        length(tCAIG);

    % MATLAB duration timestamps

    timeFOG = ...
        seconds(tFOG);

    timeCAIG = ...
        seconds(tCAIG);

    %% --------------------------------------------------------
    % Ground-truth triaxial sway
    % ---------------------------------------------------------

    OmegaA_FOG = ...
        generateLevel2Sway(tFOG);

    OmegaA_CAIG = ...
        generateLevel2Sway(tCAIG);

    % True angular rate expressed in FOG frame

    OmegaF_true = ...
        (C_A_F ...
        * OmegaA_FOG.').';

    %% --------------------------------------------------------
    % Storage for this duration
    % ---------------------------------------------------------

    finalStates = ...
        zeros(nRuns,6);

    %% --------------------------------------------------------
    % Monte Carlo loop
    % ---------------------------------------------------------

    for run = 1:nRuns

        %% ====================================================
        % FOG REALIZATION
        % ====================================================

        % Same seed per run across durations.
        %
        % Therefore shorter simulations correspond to the
        % beginning of the longer realizations.

        rng(10000 + run, ...
            'twister');

        paramsFOG = ...
            gyroparams( ...
                'ConstantBias', ...
                biasFOGvec, ...
                ...
                'NoiseDensity', ...
                N_FOG*ones(1,3), ...
                ...
                'NoiseType', ...
                'single-sided');

        imuFOG = ...
            imuSensor( ...
                'accel-gyro', ...
                ...
                'SampleRate', ...
                FsFOG, ...
                ...
                'Gyroscope', ...
                paramsFOG);

        accelDummy = ...
            zeros(NFOG,3);

        [~,OmegaFOG] = ...
            imuFOG( ...
                accelDummy, ...
                OmegaF_true);

        %% ====================================================
        % CAIG REALIZATION
        % ====================================================

        rng(20000 + run, ...
            'twister');

        caigNoise = ...
            sigmaCAIG ...
            * randn(NCAIG,3);

        OmegaCAIG = ...
            OmegaA_CAIG ...
            + caigNoise;

        %% ====================================================
        % CREATE TIMETABLES
        % ====================================================

        TT_FOG = ...
            timetable( ...
                OmegaFOG(:,1), ...
                OmegaFOG(:,2), ...
                OmegaFOG(:,3), ...
                ...
                'RowTimes', ...
                timeFOG, ...
                ...
                'VariableNames',{ ...
                    'OmegaX', ...
                    'OmegaY', ...
                    'OmegaZ'});

        TT_CAIG = ...
            timetable( ...
                OmegaCAIG(:,1), ...
                OmegaCAIG(:,2), ...
                OmegaCAIG(:,3), ...
                ...
                'RowTimes', ...
                timeCAIG, ...
                ...
                'VariableNames',{ ...
                    'OmegaX', ...
                    'OmegaY', ...
                    'OmegaZ'});

        %% ====================================================
        % RETIME FOG TO CAIG EPOCHS
        % ====================================================

        TT_FOG_at_CAIG = ...
            retime( ...
                TT_FOG, ...
                TT_CAIG.Properties.RowTimes, ...
                'linear');

        OmegaFOG_CAIG = ...
            [ ...
                TT_FOG_at_CAIG.OmegaX, ...
                TT_FOG_at_CAIG.OmegaY, ...
                TT_FOG_at_CAIG.OmegaZ ...
            ];

        %% ====================================================
        % VALIDATE AGAINST OLD MANUAL INDEXING
        % ====================================================

        % The manual method is used ONLY as a validation path.
        %
        % It does not feed the Kalman estimator.

        idxManual = ...
            1:sampleRatio:NFOG;

        OmegaFOG_manual = ...
            OmegaFOG(idxManual,:);

        methodDifference = ...
            OmegaFOG_CAIG ...
            - OmegaFOG_manual;

        maxMethodDifferenceAll(d,run,:) = ...
            max( ...
                abs(methodDifference), ...
                [], ...
                1);

        timeDifference = ...
            TT_FOG_at_CAIG.Properties.RowTimes ...
            - TT_CAIG.Properties.RowTimes;

        maxTimeDifferenceAll(d,run) = ...
            max( ...
                abs( ...
                    seconds(timeDifference)));

        %% ====================================================
        % MONITORING OBSERVATION
        % ====================================================

        % Zhang observation:
        %
        % Z = FOG - CAIG

        Z = ...
            OmegaFOG_CAIG ...
            - OmegaCAIG;

        %% ====================================================
        % KALMAN INITIALIZATION
        % ====================================================

        Xhat = ...
            X0;

        P = ...
            P0;

        %% ====================================================
        % KALMAN LOOP
        % ====================================================

        for k = 1:NCAIG

            % -----------------------------------------------
            % Prediction
            % -----------------------------------------------

            Xpred = ...
                Phi ...
                * Xhat;

            Ppred = ...
                Phi ...
                * P ...
                * Phi.' ...
                + Q;

            % -----------------------------------------------
            % Measurement matrix
            % -----------------------------------------------

            % True simulated angular rate is intentionally
            % used in H.
            %
            % This isolates the Zhang linear observation model
            % from errors-in-variables effects.

            omega = ...
                OmegaA_CAIG(k,:).';

            H = ...
                [ ...
                    skewMatrix(omega), ...
                    eye(3) ...
                ];

            % -----------------------------------------------
            % Measurement
            % -----------------------------------------------

            z = ...
                Z(k,:).';

            % -----------------------------------------------
            % Innovation
            % -----------------------------------------------

            innovation = ...
                z ...
                - H*Xpred;

            % -----------------------------------------------
            % Innovation covariance
            % -----------------------------------------------

            S = ...
                H ...
                * Ppred ...
                * H.' ...
                + R;

            % -----------------------------------------------
            % Kalman gain
            % -----------------------------------------------

            K = ...
                Ppred ...
                * H.' ...
                / S;

            % -----------------------------------------------
            % State update
            % -----------------------------------------------

            Xhat = ...
                Xpred ...
                + K*innovation;

            % -----------------------------------------------
            % Joseph covariance update
            % -----------------------------------------------

            P = ...
                (I6-K*H) ...
                * Ppred ...
                * (I6-K*H).' ...
                ...
                + K ...
                * R ...
                * K.';

        end

        %% ====================================================
        % SAVE FINAL STATE
        % ====================================================

        finalStates(run,:) = ...
            Xhat.';

    end

    %% --------------------------------------------------------
    % Convert Monte Carlo results
    % ---------------------------------------------------------

    phiEstDeg = ...
        rad2deg( ...
            finalStates(:,1:3));

    biasEstDeg_h = ...
        rad2deg( ...
            finalStates(:,4:6)) ...
        *3600;

    truePhi = ...
        phiTrueDeg.';

    trueBias = ...
        biasFOG_deg_h ...
        * ones(1,3);

    %% --------------------------------------------------------
    % Misalignment statistics
    % ---------------------------------------------------------

    meanPhi = ...
        mean( ...
            phiEstDeg, ...
            1);

    stdPhi = ...
        std( ...
            phiEstDeg, ...
            0, ...
            1);

    rmsePhi = ...
        sqrt( ...
            mean( ...
                (phiEstDeg-truePhi).^2, ...
                1));

    ciPhiLow = ...
        meanPhi ...
        - 1.96 ...
        * stdPhi ...
        / sqrt(nRuns);

    ciPhiHigh = ...
        meanPhi ...
        + 1.96 ...
        * stdPhi ...
        / sqrt(nRuns);

    %% --------------------------------------------------------
    % FOG-bias statistics
    % ---------------------------------------------------------

    meanBias = ...
        mean( ...
            biasEstDeg_h, ...
            1);

    stdBias = ...
        std( ...
            biasEstDeg_h, ...
            0, ...
            1);

    rmseBias = ...
        sqrt( ...
            mean( ...
                (biasEstDeg_h-trueBias).^2, ...
                1));

    ciBiasLow = ...
        meanBias ...
        - 1.96 ...
        * stdBias ...
        / sqrt(nRuns);

    ciBiasHigh = ...
        meanBias ...
        + 1.96 ...
        * stdBias ...
        / sqrt(nRuns);

    %% --------------------------------------------------------
    % Save duration results
    % ---------------------------------------------------------

    meanPhi_all(d,:) = ...
        meanPhi;

    stdPhi_all(d,:) = ...
        stdPhi;

    rmsePhi_all(d,:) = ...
        rmsePhi;

    ciPhiLow_all(d,:) = ...
        ciPhiLow;

    ciPhiHigh_all(d,:) = ...
        ciPhiHigh;


    meanBias_all(d,:) = ...
        meanBias;

    stdBias_all(d,:) = ...
        stdBias;

    rmseBias_all(d,:) = ...
        rmseBias;

    ciBiasLow_all(d,:) = ...
        ciBiasLow;

    ciBiasHigh_all(d,:) = ...
        ciBiasHigh;

    %% --------------------------------------------------------
    % Print duration results
    % ---------------------------------------------------------

    axesNames = ...
        {'X','Y','Z'};

    fprintf('\nMISALIGNMENT\n');

    for ax = 1:3

        fprintf( ...
            '%s: mean = %.6f deg | std = %.6f | RMSE = %.6f\n', ...
            axesNames{ax}, ...
            meanPhi(ax), ...
            stdPhi(ax), ...
            rmsePhi(ax));

    end

    fprintf('\nFOG BIAS\n');

    for ax = 1:3

        fprintf( ...
            '%s: mean = %.6f deg/h | std = %.6f | RMSE = %.6f\n', ...
            axesNames{ax}, ...
            meanBias(ax), ...
            stdBias(ax), ...
            rmseBias(ax));

        fprintf( ...
            '   95%% CI mean = [%.6f, %.6f] deg/h\n', ...
            ciBiasLow(ax), ...
            ciBiasHigh(ax));

    end

    fprintf('\n');

end

%% ============================================================
% 11. GLOBAL TIMETABLE VALIDATION
% =============================================================

% Maximum over:
%
% all durations
% all Monte Carlo runs

globalMaxMethodDifference = ...
    squeeze( ...
        max( ...
            max( ...
                maxMethodDifferenceAll, ...
                [], ...
                2), ...
            [], ...
            1));

globalMaxMethodDifference = ...
    globalMaxMethodDifference(:).';

globalMaxTimeDifference = ...
    max( ...
        maxTimeDifferenceAll(:));

fprintf('============================================\n');
fprintf('TIMETABLE VALIDATION\n');
fprintf('============================================\n\n');

fprintf('Maximum timetable vs manual difference\n');

fprintf('X = %.6e rad/s\n', ...
    globalMaxMethodDifference(1));

fprintf('Y = %.6e rad/s\n', ...
    globalMaxMethodDifference(2));

fprintf('Z = %.6e rad/s\n\n', ...
    globalMaxMethodDifference(3));

fprintf('Maximum timestamp difference = %.6e s\n\n', ...
    globalMaxTimeDifference);

%% ============================================================
% 12. FINAL DURATION SUMMARY
% =============================================================

fprintf('============================================\n');
fprintf('FINAL DURATION SUMMARY - FOG BIAS\n');
fprintf('============================================\n\n');

for d = 1:nDur

    fprintf('Duration = %.0f s\n', ...
        durations(d));

    fprintf( ...
        'Mean = [%.6f %.6f %.6f] deg/h\n', ...
        meanBias_all(d,1), ...
        meanBias_all(d,2), ...
        meanBias_all(d,3));

    fprintf( ...
        'Std  = [%.6f %.6f %.6f] deg/h\n', ...
        stdBias_all(d,1), ...
        stdBias_all(d,2), ...
        stdBias_all(d,3));

    fprintf( ...
        'RMSE = [%.6f %.6f %.6f] deg/h\n', ...
        rmseBias_all(d,1), ...
        rmseBias_all(d,2), ...
        rmseBias_all(d,3));

    fprintf( ...
        'CI X = [%.6f %.6f]\n', ...
        ciBiasLow_all(d,1), ...
        ciBiasHigh_all(d,1));

    fprintf( ...
        'CI Y = [%.6f %.6f]\n', ...
        ciBiasLow_all(d,2), ...
        ciBiasHigh_all(d,2));

    fprintf( ...
        'CI Z = [%.6f %.6f]\n\n', ...
        ciBiasLow_all(d,3), ...
        ciBiasHigh_all(d,3));

end

%% ============================================================
% 13. FINAL DURATION TABLE
% =============================================================

DurationTable = ...
    table( ...
        durations.', ...
        ...
        meanBias_all(:,1), ...
        meanBias_all(:,2), ...
        meanBias_all(:,3), ...
        ...
        stdBias_all(:,1), ...
        stdBias_all(:,2), ...
        stdBias_all(:,3), ...
        ...
        rmseBias_all(:,1), ...
        rmseBias_all(:,2), ...
        rmseBias_all(:,3), ...
        ...
        'VariableNames',{ ...
            'Duration_s', ...
            ...
            'Mean_X_deg_h', ...
            'Mean_Y_deg_h', ...
            'Mean_Z_deg_h', ...
            ...
            'Std_X_deg_h', ...
            'Std_Y_deg_h', ...
            'Std_Z_deg_h', ...
            ...
            'RMSE_X_deg_h', ...
            'RMSE_Y_deg_h', ...
            'RMSE_Z_deg_h'});

disp(DurationTable);

%% ============================================================
% 14. MISALIGNMENT SUMMARY TABLE
% =============================================================

MisalignmentDurationTable = ...
    table( ...
        durations.', ...
        ...
        meanPhi_all(:,1), ...
        meanPhi_all(:,2), ...
        meanPhi_all(:,3), ...
        ...
        stdPhi_all(:,1), ...
        stdPhi_all(:,2), ...
        stdPhi_all(:,3), ...
        ...
        rmsePhi_all(:,1), ...
        rmsePhi_all(:,2), ...
        rmsePhi_all(:,3), ...
        ...
        'VariableNames',{ ...
            'Duration_s', ...
            ...
            'MeanPhi_X_deg', ...
            'MeanPhi_Y_deg', ...
            'MeanPhi_Z_deg', ...
            ...
            'StdPhi_X_deg', ...
            'StdPhi_Y_deg', ...
            'StdPhi_Z_deg', ...
            ...
            'RMSEPhi_X_deg', ...
            'RMSEPhi_Y_deg', ...
            'RMSEPhi_Z_deg'});

disp(' ');
disp('MISALIGNMENT DURATION SUMMARY');
disp(MisalignmentDurationTable);

%% ============================================================
% 15. PLOT - MEAN FOG BIAS
% =============================================================

figure;

plot( ...
    durations, ...
    meanBias_all(:,1), ...
    '-o', ...
    'LineWidth',1.2);

hold on;

plot( ...
    durations, ...
    meanBias_all(:,2), ...
    '-o', ...
    'LineWidth',1.2);

plot( ...
    durations, ...
    meanBias_all(:,3), ...
    '-o', ...
    'LineWidth',1.2);

yline( ...
    biasFOG_deg_h, ...
    '--');

xlabel('Observation duration [s]');

ylabel( ...
    'Mean FOG bias estimate [deg/h]');

title( ...
    'Mean FOG Bias Estimate vs Observation Duration - Timetable');

legend( ...
    'X', ...
    'Y', ...
    'Z', ...
    'True bias', ...
    'Location','best');

grid on;

%% ============================================================
% 16. PLOT - FOG BIAS STANDARD DEVIATION
% =============================================================

figure;

plot( ...
    durations, ...
    stdBias_all(:,1), ...
    '-o', ...
    'LineWidth',1.2);

hold on;

plot( ...
    durations, ...
    stdBias_all(:,2), ...
    '-o', ...
    'LineWidth',1.2);

plot( ...
    durations, ...
    stdBias_all(:,3), ...
    '-o', ...
    'LineWidth',1.2);

xlabel('Observation duration [s]');

ylabel('FOG bias std [deg/h]');

title( ...
    'FOG Bias Standard Deviation vs Observation Duration - Timetable');

legend( ...
    'X', ...
    'Y', ...
    'Z', ...
    'Location','best');

grid on;

%% ============================================================
% 17. PLOT - FOG BIAS RMSE
% =============================================================

figure;

plot( ...
    durations, ...
    rmseBias_all(:,1), ...
    '-o', ...
    'LineWidth',1.2);

hold on;

plot( ...
    durations, ...
    rmseBias_all(:,2), ...
    '-o', ...
    'LineWidth',1.2);

plot( ...
    durations, ...
    rmseBias_all(:,3), ...
    '-o', ...
    'LineWidth',1.2);

xlabel('Observation duration [s]');

ylabel('FOG bias RMSE [deg/h]');

title( ...
    'FOG Bias RMSE vs Observation Duration - Timetable');

legend( ...
    'X', ...
    'Y', ...
    'Z', ...
    'Location','best');

grid on;

%% ============================================================
% 18. PLOT - MISALIGNMENT RMSE
% =============================================================

figure;

plot( ...
    durations, ...
    rmsePhi_all(:,1), ...
    '-o', ...
    'LineWidth',1.2);

hold on;

plot( ...
    durations, ...
    rmsePhi_all(:,2), ...
    '-o', ...
    'LineWidth',1.2);

plot( ...
    durations, ...
    rmsePhi_all(:,3), ...
    '-o', ...
    'LineWidth',1.2);

xlabel('Observation duration [s]');

ylabel('Misalignment RMSE [deg]');

title( ...
    'Misalignment RMSE vs Observation Duration - Timetable');

legend( ...
    'X', ...
    'Y', ...
    'Z', ...
    'Location','best');

grid on;

%% ============================================================
% LOCAL FUNCTIONS
% =============================================================

function Omega = generateLevel2Sway(t)

    % Zhang level-2 sway parameters:
    %
    % Roll:
    %   amplitude = 0.50 deg
    %   period    = 20 s
    %
    % Pitch:
    %   amplitude = 0.20 deg
    %   period    = 30 s
    %
    % Heading:
    %   amplitude = 0.30 deg
    %   period    = 30 s
    %
    % Zhang provides amplitudes and periods but does not
    % provide the exact time-domain waveform.
    %
    % Sinusoidal motion is therefore a project assumption.

    rollAmp = ...
        deg2rad(0.50);

    pitchAmp = ...
        deg2rad(0.20);

    headingAmp = ...
        deg2rad(0.30);

    rollPeriod = ...
        20;

    pitchPeriod = ...
        30;

    headingPeriod = ...
        30;

    wr = ...
        2*pi/rollPeriod;

    wp = ...
        2*pi/pitchPeriod;

    wh = ...
        2*pi/headingPeriod;

    roll = ...
        rollAmp ...
        * sin(wr*t);

    pitch = ...
        pitchAmp ...
        * sin(wp*t);

    rollDot = ...
        rollAmp ...
        * wr ...
        * cos(wr*t);

    pitchDot = ...
        pitchAmp ...
        * wp ...
        * cos(wp*t);

    headingDot = ...
        headingAmp ...
        * wh ...
        * cos(wh*t);

    % 3-2-1 Euler-angle rates -> body angular rates
    %
    % p = phidot - psidot*sin(theta)
    %
    % q = thetadot*cos(phi)
    %     + psidot*sin(phi)*cos(theta)
    %
    % r = -thetadot*sin(phi)
    %     + psidot*cos(phi)*cos(theta)

    p = ...
        rollDot ...
        - headingDot ...
        .* sin(pitch);

    q = ...
        pitchDot ...
        .* cos(roll) ...
        ...
        + headingDot ...
        .* sin(roll) ...
        .* cos(pitch);

    r = ...
        -pitchDot ...
        .* sin(roll) ...
        ...
        + headingDot ...
        .* cos(roll) ...
        .* cos(pitch);

    Omega = ...
        [p q r];

end


function S = skewMatrix(v)

    % Return [v x] such that
    %
    % [v x] a = v x a

    v = ...
        v(:);

    S = ...
        [ ...
             0,     -v(3),   v(2);
             v(3),   0,     -v(1);
            -v(2),   v(1),   0 ...
        ];

end