function sync = synchronizeSensors(fog,caig,truth,cfg)
%SYNCHRONIZESENSORS Retime FOG measurements to the CAIG epochs.
%
% The timetable/retime path feeds the estimator. Manual 1:20:end indexing
% is retained only as a software-regression check.

    assert( ...
        isequal(size(fog.measured),[truth.NFOG 3]), ...
        'FOG measurements must have size truth.NFOG-by-3.');
    assert( ...
        isequal(size(caig.measured),[truth.NCAIG 3]), ...
        'CAIG measurements must have size truth.NCAIG-by-3.');

    TT_FOG = timetable( ...
        fog.measured(:,1), ...
        fog.measured(:,2), ...
        fog.measured(:,3), ...
        'RowTimes',truth.timeFOG, ...
        'VariableNames',{'OmegaX','OmegaY','OmegaZ'});

    TT_CAIG = timetable( ...
        caig.measured(:,1), ...
        caig.measured(:,2), ...
        caig.measured(:,3), ...
        'RowTimes',truth.timeCAIG, ...
        'VariableNames',{'OmegaX','OmegaY','OmegaZ'});

    TT_FOG_at_CAIG = retime( ...
        TT_FOG,TT_CAIG.Properties.RowTimes,'linear');

    assert( ...
        height(TT_FOG_at_CAIG) == truth.NCAIG, ...
        'Retimed FOG data must contain one row per CAIG epoch.');

    OmegaFOG_at_CAIG = [ ...
        TT_FOG_at_CAIG.OmegaX, ...
        TT_FOG_at_CAIG.OmegaY, ...
        TT_FOG_at_CAIG.OmegaZ ...
    ];

    idxManual = 1:cfg.sampleRatio:truth.NFOG;
    OmegaFOG_manual = fog.measured(idxManual,:);

    syncDifference = OmegaFOG_at_CAIG-OmegaFOG_manual;
    maxSyncDifference = max(abs(syncDifference),[],1);

    timeDifference = ...
        TT_FOG_at_CAIG.Properties.RowTimes ...
        -TT_CAIG.Properties.RowTimes;
    maxTimestampError = max(abs(seconds(timeDifference)));

    deltaOmega = OmegaFOG_at_CAIG-caig.measured;

    sync.TT_FOG = TT_FOG;
    sync.TT_CAIG = TT_CAIG;
    sync.TT_FOG_at_CAIG = TT_FOG_at_CAIG;
    sync.OmegaFOG_at_CAIG = OmegaFOG_at_CAIG;
    sync.deltaOmega = deltaOmega;
    sync.manualIndices = idxManual;
    sync.OmegaFOG_manual = OmegaFOG_manual;
    sync.syncDifference = syncDifference;
    sync.maxSyncDifference = maxSyncDifference;
    sync.maxTimestampError = maxTimestampError;
end
